language: bash

dist: xenial

cache:
  directories:
  - /usr/local/src

before_install:
  - rm -rf ~/.gnupg

before_script:
  - sudo apt-get -qq autoremove
  - sudo apt-get update -q

script:
  - lsb_release -a
  - sudo echo "Travis Banch = $TRAVIS_BRANCH"
  - sudo apt-get install -y --force-yes git nginx curl wget ccze
  - sudo bash nginx-build.sh --stable $TRAVIS_BRANCH || sudo bash -c 'tail -n 50 /tmp/nginx-ee.log | ccze -A' && exit 1
  - sudo bash nginx-build.sh $TRAVIS_BRANCH || sudo bash -c 'tail -n 50 /tmp/nginx-ee.log | ccze -A' && exit 1
  - sudo bash nginx-build.sh $TRAVIS_BRANCH || sudo bash -c 'tail -n 50 /tmp/nginx-ee.log | ccze -A' && exit 1
  - sudo bash nginx-build.sh --full $TRAVIS_BRANCH || sudo bash -c 'tail -n 50 /tmp/nginx-ee.log | ccze -A' && exit 1
  - sudo chown -R travis /usr/local/src
  - sudo chmod 755 /usr/local/src